mlbench/mlbench-core

docs/api.rst, docs/clientapi.rst, mlbench_core/__init__.py, mlbench_core/api.py, requirements.txt
=> Api client

mlbench_core/__init__.py, mlbench_core/controlflow/pytorch/controlflow.py, mlbench_core/dataset/imagerecognition/pytorch/__init__.py, mlbench_core/dataset/imagerecognition/pytorch/dataloader.py, mlbench_core/lr_scheduler/pytorch/lr.py, mlbench_core/models/pytorch/resnet.py, mlbench_core/utils/pytorch/__init__.py, mlbench_core/utils/pytorch/checkpoint.py, mlbench_core/utils/pytorch/distributed.py, mlbench_core/utils/pytorch/helpers.py, mlbench_core/utils/pytorch/topology.py, setup.cfg, setup.py
Removes most uses of `config` object since it hides needed parameters from users and makes it difficult to use functionality in isolation. 
Refactors `controlflow.TrainValidation` so as not to pass as many parameters between functions.
Fixes some minor bugs
=> Refactoring

mlbench_core/controlflow/tensorflow/train_validation.py, mlbench_core/dataset/imagerecognition/tensorflow/cifar10.py, mlbench_core/models/tensorflow/resnet_model.py, mlbench_core/utils/tensorflow/__init__.py
Implemented synchronized training in TF.
* The measured top-1 Accuracy in [mlbench-benchmarks](https://github.com/mlbench/mlbench-benchmarks/tree/9450bb7517c5406108fdca686372f432d7efa069) is close to 91.5%.
* Note that this implementation is not exactly equivalent to PyTorch-MPI. The SyncReplicasOptimizer guarantees the models across nodes are the same but does not guarantee that all nodes contribute equally. Use Horovod or equivalent to train with MPI backend.
=> Synchronized Training (Resnet) In TensorFlow

mlbench_core/lr_scheduler/pytorch/__init__.py, mlbench_core/lr_scheduler/pytorch/lr.py
Here I added a new learning rate scheduler (alpha/sqrt(t)) and changed the name of one of the previous LR schedulers.
=> new learning rate scheduler

.pyup.yml, mlbench_core/__init__.py, mlbench_core/api.py, mlbench_core/cli/__init__.py, mlbench_core/cli/cli.py, mlbench_core/utils/tracker.py, requirements.txt, setup.cfg, setup.py, tests/test_api.py, tests/test_utils.py
Adds cli interface for mlbench
=> Mlbench cli

mlbench_core/__init__.py, setup.cfg, setup.py
=> Fix version bumping

mlbench_core/optim/pytorch/optim.py
I added a class for a centralized Adam implementation. It uses the same logic as CentralizedSGD.
=> Adds centralized Adam implementation

mlbench_core/__init__.py, mlbench_core/api.py, mlbench_core/cli/cli.py, mlbench_core/utils/pytorch/helpers.py, setup.cfg, setup.py, tests/test_api.py
This PR adds the possibility to chose the backend when running a benchmark task.
Linked to [#35](https://github.com/mlbench/mlbench-benchmarks/pull/35) in `mlbench-benchmarks`
and  [#22](https://github.com/mlbench/mlbench-dashboard/pull/22) in `mlbench-dashboard`
=> Cli adaptation

mlbench_core/cli/cli.py
=> Add default name of output file in CLI

mlbench_core/cli/cli.py
This resolves #56. I am not sure if pickle is the right format we want to use or if there is a better way.
=> Remember user input in mlbench run

mlbench_core/utils/pytorch/distributed.py
This PR removes redundant code from `pack_tensors`.
=> Refactor pack_tensors

mlbench_core/cli/cli.py
Changes default GPU type to `nvidia-tesla-k80`
=> changed default gpu to k80

mlbench_core/cli/cli.py
Adds `--version` flag, resolves #97
=> add --version flag

mlbench_core/cli/cli.py
=> status: make name optional, list all runs if missing

mlbench_core/cli/cli.py, requirements.txt, setup.py, tox.ini
This resolves #33.
**NOTE**: Currently, only CPU is supported because I can't use GPUs with my account. I created #104 to resolve this. I will try to pick up that issue when I get AWS quota increase.
=> Add AWS support in CLI

mlbench_core/cli/cli.py, tox.ini
Closes #91 
Also fixes an issue with gcloud cluster creation
=> Adds support for multiple clusters

mlbench_core/cli/aws_utils.py, mlbench_core/cli/cli.py
Fixes the problems with deploying on AWS after the latest updates. 
We have to note somewhere that the program needs write access to the kube config location and that the user needs to install aws-iam-authenticator in order for this to work. @ehoelzl where do you think we should put this?
=> Fix AWS deployment

.codecov.yml, mlbench_core/__init__.py, mlbench_core/dataset/nlp/pytorch/wmt16/preprocess/preprocess.py, mlbench_core/dataset/nlp/pytorch/wmt16/wmt16_tokenizer.py, mlbench_core/evaluation/pytorch/criterion.py, mlbench_core/models/pytorch/transformer/decoder.py, mlbench_core/models/pytorch/transformer/encoder.py, mlbench_core/models/pytorch/transformer/modules/embeddings.py, mlbench_core/models/pytorch/transformer/modules/layers.py, mlbench_core/models/pytorch/transformer/sequence_generator.py, mlbench_core/models/pytorch/transformer/transformer.py, mlbench_core/utils/pytorch/inference/beam_search.py, setup.cfg, setup.py
Fixes the translators (PyTorch 1.7.0)
Closes #223 and preferred over #224 as it fixes also the beam search
=> Fix translators

mlbench_core/controlflow/pytorch/controlflow.py, mlbench_core/controlflow/pytorch/train_validation.py, mlbench_core/evaluation/pytorch/metrics.py, setup.py, tests/test_pytorch_controlflow.py, tests/test_pytorch_metrics.py
=> Remove loss from metric argument

.github/workflows/python-app.yml
Travis CI have changed their billing policy. Github Actions is free
=> Switch to github actions
